package com.lc.pojo;
// Generated 2019-12-18 19:47:14 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clazz generated by hbm2java
 */
public class Clazz implements java.io.Serializable {

	private int cno;
	private String cname;
	private Set students = new HashSet(0);
	private Set levels = new HashSet(0);

	public Clazz() {
	}

	public Clazz(int cno) {
		this.cno = cno;
	}

	public Clazz(int cno, String cname, Set students, Set levels) {
		this.cno = cno;
		this.cname = cname;
		this.students = students;
		this.levels = levels;
	}

	public int getCno() {
		return this.cno;
	}

	public void setCno(int cno) {
		this.cno = cno;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

	public Set getLevels() {
		return this.levels;
	}

	public void setLevels(Set levels) {
		this.levels = levels;
	}

}
