package com.lc.pojo;
// Generated 2019-12-18 19:47:14 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Kaoqin generated by hbm2java
 */
public class Kaoqin implements java.io.Serializable {

	private int kid;
	private String kname;
	private Set kaoqinrecords = new HashSet(0);

	public Kaoqin() {
	}

	public Kaoqin(int kid) {
		this.kid = kid;
	}

	public Kaoqin(int kid, String kname, Set kaoqinrecords) {
		this.kid = kid;
		this.kname = kname;
		this.kaoqinrecords = kaoqinrecords;
	}

	public int getKid() {
		return this.kid;
	}

	public void setKid(int kid) {
		this.kid = kid;
	}

	public String getKname() {
		return this.kname;
	}

	public void setKname(String kname) {
		this.kname = kname;
	}

	public Set getKaoqinrecords() {
		return this.kaoqinrecords;
	}

	public void setKaoqinrecords(Set kaoqinrecords) {
		this.kaoqinrecords = kaoqinrecords;
	}

}
