package com.lc.pojo;
// Generated 2019-12-18 19:47:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kaoqinrecord generated by hbm2java
 */
public class Kaoqinrecord implements java.io.Serializable {

	private int krid;
	private Kaoqin kaoqin;
	private Date kdate;
	private Set tests = new HashSet(0);

	public Kaoqinrecord() {
	}

	public Kaoqinrecord(int krid) {
		this.krid = krid;
	}

	public Kaoqinrecord(int krid, Kaoqin kaoqin, Date kdate, Set tests) {
		this.krid = krid;
		this.kaoqin = kaoqin;
		this.kdate = kdate;
		this.tests = tests;
	}

	public int getKrid() {
		return this.krid;
	}

	public void setKrid(int krid) {
		this.krid = krid;
	}

	public Kaoqin getKaoqin() {
		return this.kaoqin;
	}

	public void setKaoqin(Kaoqin kaoqin) {
		this.kaoqin = kaoqin;
	}

	public Date getKdate() {
		return this.kdate;
	}

	public void setKdate(Date kdate) {
		this.kdate = kdate;
	}

	public Set getTests() {
		return this.tests;
	}

	public void setTests(Set tests) {
		this.tests = tests;
	}

}
