package com.lc.pojo;
// Generated 2019-12-18 19:47:14 by Hibernate Tools 4.3.5.Final

/**
 * Level generated by hbm2java
 */
public class Level implements java.io.Serializable {

	private int lid;
	private Clazz clazz;
	private String lname;
	private String month;

	public Level() {
	}

	public Level(int lid) {
		this.lid = lid;
	}

	public Level(int lid, Clazz clazz, String lname, String month) {
		this.lid = lid;
		this.clazz = clazz;
		this.lname = lname;
		this.month = month;
	}

	public int getLid() {
		return this.lid;
	}

	public void setLid(int lid) {
		this.lid = lid;
	}

	public Clazz getClazz() {
		return this.clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

}
