package com.lc.pojo;
// Generated 2019-12-18 19:47:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int sid;
	private Clazz clazz;
	private String sname;
	private String sex;
	private String idcard;
	private Date intime;
	private String sphone;
	private String saddress;
	private String school;
	private String smajor;
	private Date outtime;
	private Set tests = new HashSet(0);

	public Student() {
	}

	public Student(int sid) {
		this.sid = sid;
	}

	public Student(int sid, Clazz clazz, String sname, String sex, String idcard, Date intime, String sphone,
			String saddress, String school, String smajor, Date outtime, Set tests) {
		this.sid = sid;
		this.clazz = clazz;
		this.sname = sname;
		this.sex = sex;
		this.idcard = idcard;
		this.intime = intime;
		this.sphone = sphone;
		this.saddress = saddress;
		this.school = school;
		this.smajor = smajor;
		this.outtime = outtime;
		this.tests = tests;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public Clazz getClazz() {
		return this.clazz;
	}

	public void setClazz(Clazz clazz) {
		this.clazz = clazz;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	public Date getIntime() {
		return this.intime;
	}

	public void setIntime(Date intime) {
		this.intime = intime;
	}

	public String getSphone() {
		return this.sphone;
	}

	public void setSphone(String sphone) {
		this.sphone = sphone;
	}

	public String getSaddress() {
		return this.saddress;
	}

	public void setSaddress(String saddress) {
		this.saddress = saddress;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getSmajor() {
		return this.smajor;
	}

	public void setSmajor(String smajor) {
		this.smajor = smajor;
	}

	public Date getOuttime() {
		return this.outtime;
	}

	public void setOuttime(Date outtime) {
		this.outtime = outtime;
	}

	public Set getTests() {
		return this.tests;
	}

	public void setTests(Set tests) {
		this.tests = tests;
	}

}
