package com.lc.pojo;
// Generated 2019-12-18 19:47:14 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private int tid;
	private Kaoqinrecord kaoqinrecord;
	private Student student;
	private Float tscore;
	private Date tdate;

	public Test() {
	}

	public Test(int tid) {
		this.tid = tid;
	}

	public Test(int tid, Kaoqinrecord kaoqinrecord, Student student, Float tscore, Date tdate) {
		this.tid = tid;
		this.kaoqinrecord = kaoqinrecord;
		this.student = student;
		this.tscore = tscore;
		this.tdate = tdate;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public Kaoqinrecord getKaoqinrecord() {
		return this.kaoqinrecord;
	}

	public void setKaoqinrecord(Kaoqinrecord kaoqinrecord) {
		this.kaoqinrecord = kaoqinrecord;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Float getTscore() {
		return this.tscore;
	}

	public void setTscore(Float tscore) {
		this.tscore = tscore;
	}

	public Date getTdate() {
		return this.tdate;
	}

	public void setTdate(Date tdate) {
		this.tdate = tdate;
	}

}
